### ISSUE TITLE
Add options to select modules to load

### ISSUE THREAD

**Issue by andresrinivasan** [RedisLabs/RedisEdge#4]
E.g. if a TensorFlow model isn't going to be used, there is no need to load the RedisAI module.

**Comment by itamarhaber** [comment]
How would you make such an option available? In any case, you can override the default CMD with command line arguments or by providing a custom conf file.

**Comment by andresrinivasan** [comment]
I'm thinking we can make it easier with an environment variable enumerating the modules you want.

**Comment by itamarhaber** [comment]
Why are (enumerated) env vars preferable to a custom config file? I think we should move to a config file regardless as the current setup doesn't persist anything. Once the image makes use of a conf file with modules loaded in it, customizing it is just a matter of editing it.

**Comment by andresrinivasan** [comment]
I believe we're basically saying the same thing and the slight difference is I'm suggesting we find a way to avoid editing the conf file. My thinking is the default is to load everything and we can override from the environment.

**Comment by itamarhaber** [comment]
Pursuant to our Slack call, please refer to the current master branch that uses a custom conf file.
